services:
    #tuto.uploadFile:
     #       class: TutoBundle\Service\uploadFile
      #      arguments:
       #          $targetDir: %image_directory%

    #TutoBundle\Infrastructure\FileController:
     #                         public: true
      #                        tags:
       #                           - name: controller.service_arguments
        #                            action: uploadFile
         #                           argument: uploadFile
          #                          id: tuto.uploadFile

