<?php

namespace TutoBundle\Repository;

/**
 * baseRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class baseRepository extends \Doctrine\ORM\EntityRepository
{
    public  function FindAllPaginator()
    {
        return $this->createQueryBuilder('a')
                    ->getQuery();
    }
}
