<?php

namespace TutoBundle\Repository;

/**
 * noteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class noteRepository extends \Doctrine\ORM\EntityRepository
{
    public  function FindQueribuilder($id)
    {
        return $this->createQueryBuilder('n')
            ->Join('n.etudiant','e')
            ->Join('n.matiere','m')
            ->where('e.id= :id')
            ->setParameter('id',$id)
            ->addSelect('e')
            ->addSelect('m')
            ->getQuery()
            ->getResult(); //mreturn objet
            //->getArrayResult() mreturn sous forme tableau
            // ->getScalarResult() mreturn sous forme tableau f tableau tsotra
    }


    public function FindDQL($id)
    {
        $query = $this->_em->createQuery('select n.note,upper(e.nom) AS NOM,e.prenom,m.nomMatiere from TutoBundle:note n join n.etudiant e join n.matiere m WHERE e.id= :id');
        $query->setParameter('id',$id);
        $result = $query->getResult();
        return $result;
    }


}
