<?php

namespace TutoBundle\Repository;

/**
 * paroleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class paroleRepository extends \Doctrine\ORM\EntityRepository
{
}
